library(Seurat)
library(tidyverse)
library(patchwork)
library(reshape2)
library(cowplot) #for plot_grid


# script to calculate percentage of mitochondrial reads for quality control filtering of cells
# input is digital expression matrix (DGE) generated by the dropseq alignment pipeline
# output is a file with mitochondrial reads quantification that is used in main analysis script

read_DGE_mito<-function (file_path,prefix){
  n<-ncol(read.table(file = file_path))
  Q<-read.table(file = file_path, header = TRUE, row.names = 1, colClasses =c("character", rep("numeric", n-1)))
  Q.tb<-as_tibble(rownames_to_column(Q, var = "name"))
  Q.tb<-Q.tb %>% setNames(paste0(prefix,colnames(Q.tb))) %>% rename(name = paste(prefix,"name",sep=""))
  return(Q.tb)
}

join_DGE_Quadrants<-function(Q1,Q2,Q3,Q4) {
  Q1_Q2<-full_join(Q1, Q2, by = "name")
  Q3_Q4<-full_join(Q3, Q4, by = "name")
  merged_quads<-full_join(Q1_Q2, Q3_Q4, by = "name") %>% replace(is.na(.), 0)
  return(merged_quads)
}

####################
# LOAD DATA FROM DGE
####################

P103.Q1.mito<-read_DGE_mito("SCR-M1-00103-Q1-Pool.dge.txt","Plate103.Q1.")
P103.Q2.mito<-read_DGE_mito("SCR-M1-00103-Q2-Pool.dge.txt","Plate103.Q2.")
P103.Q3.mito<-read_DGE_mito("SCR-M1-00103-Q3-Pool.dge.txt","Plate103.Q3.")
P103.Q4.mito<-read_DGE_mito("SCR-M1-00103-Q4-Pool.dge.txt","Plate103.Q4.")

P230.Q1.mito<-read_DGE_mito("SCR-M1-00230-Q1.dge.txt","Plate230.Q1.")
P230.Q2.mito<-read_DGE_mito("SCR-M1-00230-Q2.dge.txt","Plate230.Q2.")
P230.Q3.mito<-read_DGE_mito("SCR-M1-00230-Q3.dge.txt","Plate230.Q3.")
P230.Q4.mito<-read_DGE_mito("SCR-M1-00230-Q4.dge.txt","Plate230.Q4.")


Plate103.tb.mito<-join_DGE_Quadrants(P103.Q1.mito,P103.Q2.mito,P103.Q3.mito,P103.Q4.mito)
Plate230.tb.mito<-join_DGE_Quadrants(P230.Q1.mito,P230.Q2.mito,P230.Q3.mito,P230.Q4.mito)

################################################################################################
# MERGED SEURAT OBJECTS CREATED FROM EACH PLATE (RETAINING PLATE INFORMATION)--THE CORRECT WAY##
################################################################################################
#Create Seurat Objects
scRNA1.mito <- CreateSeuratObject(counts=data.frame(Plate103.tb.mito, row.names = 1), min.cells=0, min.features=0, project="rep1")
scRNA2.mito <- CreateSeuratObject(counts=data.frame(Plate230.tb.mito, row.names = 1), min.cells=0, min.features=0, project="rep2")
scRNA.both.mito<-merge(scRNA1.mito, scRNA2.mito, project = "all")


scRNA.both.mito %<>% 
  NormalizeData(normalization.method = "LogNormalize", scale.factor = 10000) %>%  
  FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>%
  RunPCA()

scRNA.both.mito[["percent.mt"]] <- PercentageFeatureSet(scRNA.both.mito, pattern = "^mt-")

mito.meta<-scRNA.both.mito@meta.data  %>%
  rownames_to_column(var = 'name') %>% 
  select(name,percent.mt) %>% 
  column_to_rownames('name') 

write.table(mito.meta, file = "Plate103_230_mito_meta.tsv",sep = "\t" )
